-- MySQL Script generated by MySQL Workbench
-- Qua 12 Jul 2017 21:12:51 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`imoveis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`imoveis` ;

CREATE TABLE IF NOT EXISTS `mydb`.`imoveis` (
  `idimoveis` INT NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(200) NOT NULL,
  `dimensoes` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `qtd_comodos` VARCHAR(45) NOT NULL,
  `responstavel` VARCHAR(45) NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idimoveis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`insumo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`insumo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`insumo` (
  `idinsumo` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `unity_medida` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idinsumo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compra_insumo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`compra_insumo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`compra_insumo` (
  `insumo` INT NOT NULL,
  `imoveis` INT NOT NULL,
  `valor_unitario` VARCHAR(45) NOT NULL,
  `valor_total` VARCHAR(45) NOT NULL,
  `data_compra` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`insumo`, `imoveis`),
  INDEX `fk_compra_insumo_imoveis1_idx` (`imoveis` ASC),
  CONSTRAINT `fk_compra_insumo_insumo`
    FOREIGN KEY (`insumo`)
    REFERENCES `mydb`.`insumo` (`idinsumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_insumo_imoveis1`
    FOREIGN KEY (`imoveis`)
    REFERENCES `mydb`.`imoveis` (`idimoveis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Data for table `mydb`.`imoveis`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`imoveis` (`idimoveis`, `endereco`, `dimensoes`, `tipo`, `qtd_comodos`, `responstavel`, `data`, `status`) VALUES (1, 'asd,asd,asd', 'asd', 'asd', '12', 'asd', 'asd', 'sdfdf');
INSERT INTO `mydb`.`imoveis` (`idimoveis`, `endereco`, `dimensoes`, `tipo`, `qtd_comodos`, `responstavel`, `data`, `status`) VALUES (2, 'dasd', 'dsad', 'dasdas', '12', 'asdd', 'asdsd', 'sdadsa');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`insumo`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`insumo` (`idinsumo`, `codigo`, `descricao`, `unity_medida`) VALUES (1, '123', 'descricao', 'asd');
INSERT INTO `mydb`.`insumo` (`idinsumo`, `codigo`, `descricao`, `unity_medida`) VALUES (2, '124', 'sdadasd', 'dsa');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`compra_insumo`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`compra_insumo` (`insumo`, `imoveis`, `valor_unitario`, `valor_total`, `data_compra`) VALUES (1, 2, '123', '321', 'asdasd');

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
